[workspace]
resolver = "2"
members = ["crates/cordn-core", "crates/cordn-server"]
exclude = ["references"]

[workspace.package]
version = "0.4.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/Cordn-msg/cordn-rs"
homepage = "https://contextvm.org"

[workspace.dependencies]
cordn-core = { path = "crates/cordn-core" }
cordn-server = { path = "crates/cordn-server" }

[profile.release]
lto = true
codegen-units = 1
strip = true
